    FROM php:8.0-apache

    RUN a2enmod rewrite

    RUN apt-get update && apt-get install -y git unzip zip

    WORKDIR /var/www/html

    COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
    RUN install-php-extensions gd pdo_mysql bcmath zip intl opcache

    COPY --from=composer:2.0 /usr/bin/composer /usr/local/bin/composer

    RUN php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"

    COPY composer.json ./

    CMD php -S 0.0.0.0:8000 public/index.php

    EXPOSE 8000